import type { InferGetServerSidePropsType, NextPage } from "next";
import { getApolloClient } from "../apollo-client";
import { CardGrid, CardLink, PokemonCard } from "../components";
import { DocumentHead } from "../models";
import styles from "../styles/Page.module.css";
import homeStyles from "../styles/Home.module.css";
import { getRandomPokemonId } from "../utils";
import {
  PokemonDocument,
  PokemonQuery,
  PokemonQueryVariables,
} from "@generated";

export const getServerSideProps = async () => {
  const documentHead: DocumentHead = {
    title: "Gotta Fetch 'em All",
    description: "Generated by create next app",
  };

  const client = getApolloClient();
  const randomPokemonId = getRandomPokemonId();

  const variables: PokemonQueryVariables = {
    id: randomPokemonId,
  };

  const { data } = await client.query<PokemonQuery>({
    query: PokemonDocument,
    variables,
  });

  return {
    props: {
      documentHead,
      pokemon: data.pokemon,
    },
  };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ pokemon }) => {
  return (
    <main className={styles.main}>
      <h1 className={styles.title}>
        Pokémon gotta{" "}
        <a href="https://wayfair.github.io/dociql/">Fetch &apos;em all</a>
      </h1>

      <p className={styles.description}>
        Hello there! Welcome to the world of pokémon! This world is inhabited by
        creatures called pokémon! For some people, pokémon are pets. Others use
        them for fights. Myself...I fetch pokémon with GraphQL.
      </p>

      <CardGrid>
        <CardLink href="/pokedex" title="Pokedex">
          <p>
            To make a complete guide on all the Pokémon in the world… That was
            my dream! But, I&apos;m too old! I can&apos;t do it! So, I want you
            to check out this page!
          </p>
        </CardLink>

        <CardLink href="/types" title="Types">
          <p>
            Looking for the different Pokémon Types? This page is for you!{" "}
            <br />
            <br />
            🐛 🐉 ⚡️ 🥊 🔥 🦅 👻 🌱 🟤 ❄️ 🐭 ☠️ 🔮 🪨 💦
          </p>
        </CardLink>

        {pokemon && (
          <div className={homeStyles.featured_pokemon}>
            <PokemonCard {...pokemon} />
          </div>
        )}
      </CardGrid>
    </main>
  );
};

export default Home;
